"""Added Model Goal.

Revision ID: 61d7672dd37e
Revises: e4ad941cbf09
Create Date: 2025-05-10 21:32:03.541894

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "61d7672dd37e"
down_revision = "e4ad941cbf09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("goal", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("goal", schema=None) as batch_op:
        batch_op.drop_column("title")

    # ### end Alembic commands ###
